services:    
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_CAPACITY_CACHE: 10
    restart: unless-stopped
    ports:
      - "8000:8000"